server:
  port: 7777

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.22a72f752925554a
            client-secret: 237c87b9bd31671e49e9df93eb158707ed49a99b
  datasource:
    url: jdbc:postgresql://localhost:2222/library_db
    username: maids
    password: maids
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

api:
  version: /api/v1

jwt:
  key: 7ab42c0c898fa0c4612166e5f829e935e2ee3084b329bd15579e525844cc3593
  access-token-expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
